styled-components/xstyled

packages/styled-components/src/styled.js
packages/system/src/systemComponent.js
packages/system/src/systemComponent.test.js
website/src/pages/docs/system-components.mdx
website/src/pages/docs/system-props.mdx

This includes a breaking change in `createSystemComponent`:
Before: `createSystemComponent(React.createElement)`
After: `createSystemComponent(React)`
Be careful!

fix: use React.forwardRef in createSystemComponent

---

website/src/pages/docs/responsive.mdx

Just started working with the library and noticed an issue with the docs.
The formatting for the responsive box was incorrect. It needs to be wrapped in another set of brackets `{}` to be made into an object, and the brackets around the `1/3` need to be removed (because it should be a direct property of `md`, not a nested one).
Should be an easy merge 👍I haven't tested this in the monorepo, just a quick edit. Let me know if I messed up the syntax 😅
- [Here is an example of copying code from the docs](https://codesandbox.io/s/xstyled-responsive-docs-issue-vw545?file=/src/App.js)
- [Here is an example of the fixed code I added to the docs](https://codesandbox.io/s/xstyled-responsive-docs-fix-l3xg6?file=/src/App.js)

Fix example in docs

---

packages/core/src/breakpoints.js

useThemeDown is exclusive so useThemeUp should be inclusive, otherwise
there's a hole when width is exactly value.
Testing amounted to staring at the code and noticing this bug while working on
something unrelated (see #114)

fix(breakpoints): useThemeUp inclusive min

---

packages/core/src/breakpoints.js

The main fix here is changing the initial state from null to
window.innerWidth, so that there isn't a useless transition from (for
example) `useDown('md') = true` to `useDown('md') = false` when the
application loads. Depending on the application, the rerendering penalty
can be heavy.
While we're here, notice that we can make a couple related changes:
First, since the initial state is set properly, we don't need a layout
effect, instead we can use a normal effect. Second, swap the order of
listener and setWidth to avoid the tiny race between them.
This cropped up for me in storybook. I have a component that measures its
container to make image layout decisions. On the first load of the app, it would
work, but on hot reload, the image would be the wrong size.
The problem is that …

fix(breakpoints): races in useViewportWidth

---

packages/system/src/styles/flexboxes.js

flex can cover `grow`, `shrink` and `basis`. Because we already have `basis`, I think it's a good idea to also add `shrink` and `grow` for consistency.

Add missing `shrink` and `grow` props

---

packages/emotion/src/index.js
packages/emotion/src/styled.test.js
yarn.lock

Makes `keyframes` from emotion available through xstyled

fix: adds keyframes to emotion exports

---

packages/prop-types/src/index.js

When composing the component styles using the `xgrids + getSystemProps` it shoots warnings in the console because the bool option is not enabled in the `@xstyled/prop-types`, it means that the props `col` and `row` will not pass the proptypes validation.
For my specific case, I work in a project where warning are not allowed in the tests and because of that the props `col` and `row` are breaking the tests
```jsx
// Component
import React from 'react'
import { PropTypes } from 'prop-types'
import { getSystemPropTypes } from '@xstyled/prop-types'
import StyledField, { systemProps } from './Field.styled'
const Field = StyledField
Field.propTypes = {
children: PropTypes.node.isRequired,
...getSystemPropTypes(systemProps),
}
export default Field
// Styles
import styled from '@xstyled/emotion' …
```

feat(prop-types): Add bool option to the prop-types to use it with col and row props

---

packages/system/src/style.js

Hello folks!
There is a bug when passing several responsive style props, the order of the resulting media queries is wrong.
More details on this in issue [#119](https://github.com/smooth-code/xstyled/issues/119)
Example 
Code:
```
<Box 
pt={{ sm: 0, lg: 60 }}
pb={{ md: 20, lg: 60 }}
bg={{ xs: 'blue', md: 'red', lg: 'green', xl: '#000000'}}
>
hello
</Box>
```
The idea is to organize the order of @medias based on the breakpoint values. A function was created to guarantee the order of the breakpoints, without the need to add complexity to the `merge` function.

fix(breakpoints): multiple responsive style props

---

packages/system/src/defaultTheme.test.ts
packages/system/src/defaultTheme.ts
website/pages/docs/sizing/height.mdx
website/pages/docs/sizing/max-height.mdx
website/pages/docs/sizing/max-width.mdx
website/pages/docs/sizing/min-height.mdx
website/pages/docs/sizing/width.mdx

Fixes: https://github.com/gregberge/xstyled/issues/162
Any size key between 0 and 1 should have a suffix "s" so it does not conflict with fluid (%) values.
This PR adds a suffix "s" to size key 0.5 on theme so it can be targeted without conflicting with fluid (50%).
I've improved the explanation on the docs of why the suffix "s" have be used.
Added a test to check if all numeric keys of theme sizes are greater than 1.

bugfix: size 0.5 conflict fluid range

---

package.json
packages/emotion/src/index.ts
packages/emotion/src/preflight.test.tsx
packages/emotion/src/preflight.tsx
website/pages/docs/getting-started/installation.mdx

The xstyled/emotion does not provide a Preflight component, like the xstyled/styled-components do.
Now we have a Preflight exported from xstyled/emotion. It utilizes the <Global> component from emotion (https://emotion.sh/docs/globals).
Created two tests, basically:
1) Make sure the Preflight component renders null (as, on client, it injects into the DOM)
2) Make sure the Preflight component inject styles into the DOM.

feature: adding preflight component to emotion

---

packages/emotion/src/jsx.test.tsx
packages/emotion/src/jsx.ts

A bug on the xstyled/emotion jsx API makes the children of tags with "css" props to not be rendered:
```javascript
<div css={{...}}>
<p>A paragraph</p> // currently, this will not be rendered
</div>
```
So, this PR fixes this issue and creates some tests to ensure its stability.
3 tests were created:
- Empty <div css={{...}} /> does not render any content
- <div css={{...}}> with a single children renders the content
- <div css={{...}}> with multiple children renders all elements 
Before:
After:

bugfix: adding children to emotion jsx function

---

website/pages/docs/customization/theme.mdx

The docs seem quite useful, but could be a tad bit misleading when the text above an example says to use the key `screens` to provide responsive breakpoints, while the example below it uses a different key (`breakpoints` in this case).
No code updated.

Updated incorrect `screens` key in the theme example

---

package.json
packages/emotion/src/createX.ts
yarn.lock

The current @xstyled/emotion/x.d.ts file is broken due to this issue on typescript:
https://github.com/microsoft/TypeScript/issues/27171
https://unpkg.com/@xstyled/emotion@2.1.0/dist/x.d.ts
If you scroll down to very bottom, you fill find a couple of "... 100 more ..." strings
This branch focuses to improve the x.d.ts file in a way that it does not generate that massive type.
Basically, the main type responsible for generating that big d.ts file is JSX.IntrinsicElements.
(Check the .D.TS tab on right panel)
Simple example of the type on v2.1.0: 
https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAIigUwIYGMYINwChcwCeYycAUgMoAaA0soQM5wC8cA1vRAGbnUB0ASQB2MKMCENg6AKIAbZCGQiGeXMgAekWHHQQJ8dClQxkVFnAAUAShYA+OAG9ccHXobx1ALkfOXcANochHDivLT0DAC6APze7mJCAOZ4LgC+5g6pqi4oMACuUEJw6nipQA
Example of …

Improve: emotion createX function typing

---

packages/emotion/src/styled.test.tsx
packages/emotion/src/styled.ts

Pass through options to emotion `styled`, fixes #202 
Added a test (failed before the code change)
I don't personally use Emotion, but this seems to work according to the documentation and test.

fix(emotion): pass options through (#202)

---

packages/system/src/styles/sizing.ts

I appreciate the recent addition of shorthands for sizing props: maxH, maxW, minH and minW. However, there's a small thing missing to make it work correctly :)
The final CSS output has incorrect property, because the `cssProperty` is not set explicitly in the `style` function's config object. Also, the types were copy-pasted incorrectly. Fixed those too for consistency.
These props
Turn into these styles

Fixed sizing style definition and types

---

README.md

A very small thing: the README link for 'Getting started' pointed to a 404 page. Pointing to `docs/installation` seems to be the most appropriate for now, unless otherwise desired. 
N/A

Update link to 'Getting Started' page

---

packages/system/src/styles/space.ts

Fixing typo in PaddingBottomProps type. It should not affect functionality because paddingBottom prop is working properly, just types are off.

fix(types): fix paddingBottop typo

---

packages/styled-components/src/createX.test.tsx
packages/styled-components/src/createX.ts

`x.div` must pass through non-system props, including props that are not valid HTML attrs, to support `as={Component}`.
This is from discussion at https://github.com/gregberge/xstyled/pull/231#issuecomment-817353699
Since I didn't file a separate issue for this, here is a codesandbox demonstrating the problem: https://codesandbox.io/s/cool-poincare-rzyyt?file=/src/App.js
Tests included

fix: x.* must pass through props for as={Component}

---

packages/emotion/src/createX.ts
packages/styled-components/src/createX.ts

Checking `propSet.has()` takes about 1/20 the time as checking `props.includes()` for the 2500+ props in xstyled v2.
Even with a shorter list, say 100 props, it's still 1/2 the time, so this perf benefit carries over from v2 to v3.
I didn't test the perf difference directly with xstyled, but simple node. All times in milliseconds.
```
> words = fs.readFileSync('/usr/share/dict/words', {encoding: 'utf8'}).trim().split(/\s+/).slice(0, 2500)
> words.length
2500
> performance.mark('A'); for (let i = 0; i < 1000; i++) {words.includes('z')}; performance.measure('', 'A')
2.639519
> wordSet = new Set(words)
> performance.mark('B'); for (let i = 0; i < 1000; i++) {wordSet.has('z')}; performance.measure('', 'B')
0.106556
```
```
> words = words.slice(0, 100)
> words.length
100
> …
```

improvement: faster shouldForwardProp

---

packages/emotion/src/createShouldForwardProp.ts
packages/emotion/src/createX.ts
packages/emotion/src/styled.test.tsx
packages/emotion/src/styled.ts
packages/styled-components/src/createShouldForwardProp.ts
packages/styled-components/src/createX.ts
packages/styled-components/src/styled.test.tsx
packages/styled-components/src/styled.ts

Fixes #240 with rule ordering instead of specificity.
<table><tr><th>INPUT</th><th>OLD OUTPUT</th><th>NEW OUTPUT</th></tr><tr><td>
```js
const Foo = styled.box`
color: green;
`
<Foo color="red" />
```
</td><td>
```css
.foo.foo {
color: red; /* ${system} */
}
.foo {
color: green;
}
```
</td><td>
```css
.foo {
color: green;
color: red; /* ${system} */
}
```
</td></tr></table>
It works like this:
```js
styled.box = styledWithGenerator('div', system).withConfig({shouldForwardProp})
```
which applies the generator at the conclusion of the given styles, so that props can override styles:
```js
styled.box`
color: green;
`
// is exactly the same as
styled.div.withConfig({shouldForwardProp})`
color: green;
${system};
`
```
My first attempt at this PR changed the signature of the `styled` function …

fix: styled.box with rule ordering instead of specificity

---

packages/core/src/transform.ts

fix(transform): IE11 doesn't support dotAll (#247)

---

packages/emotion/src/createX.ts
packages/emotion/src/styled.test.tsx

Emotion allows its consumer apps to change styles based on props. [See here](https://emotion.sh/docs/styled#changing-based-on-props). By default, emotion would prevent invalid props from being rendered to the DOM element but since xstyled is overriding the "shouldForwardProp" this functionally is being removed. 
Styled-components handle this by prefixing the prop name with a dollar sign $.  [Transient Props](https://styled-components.com/docs/api)
Do you see any downside or conflict by doing something this? @agriffis @gregberge 
My [previous PR](https://github.com/gregberge/xstyled/pull/231) was causing some issues with the "as" so this is why I just remove the ones with the $.

Add transient Props to @xstyled/emotion

---

packages/emotion/src/styled.test.tsx
packages/emotion/src/styled.ts

I misunderstood how xstyled's css function interacts with emotion's css function, so I added this complicated code in c400c70775be09033c65cb3626ce1a683198546d.
More recently, while working on #250, I discovered that it's also broken, because it converts a function argument into an array.
This simpler code does the one thing it needs to do: concat string separators to the tagged template literal corresponding to the number of generators.
It also produces a slightly more efficient result, because it does more work up front (testing `generators.length` and concatting arrays) before the resulting function, rather than every time the function runs.
Updated `styled.test.tsx` to run some tests in common between `styled.div` and `styled.box`. Without this fix, the test "works with css as object …

fix(emotion): broken getCreateStyle

---

build/rollup.config.js

Set the esbuild target so that optional chaining is transformed in the
output module.
Partial fix for #265 and #270

fix: optional chaining syntax in dist module

---

build/rollup.config.js
package.json
packages/babel-preset-emotion-css-prop/.npmignore
packages/babel-preset-emotion-css-prop/package.json
packages/core/.npmignore
packages/core/package.json
packages/emotion/.npmignore
packages/emotion/package.json
packages/prop-types/.npmignore
packages/prop-types/package.json
packages/styled-components/.npmignore
packages/system/.npmignore
packages/system/package.json
packages/util/.npmignore
packages/util/package.json

moved away from using `.mjs` files extension for es-modules as it seems that there are some compatibility issues with It 
This code doesn't change any functionality, I ran the tests, and they all pass.

fix: move away from mjs extension to work in more environments

---

packages/styled-components/package.json

Hi, this should fix the problem with importing '@xstyled/styled-components' using [Snowpack](https://www.snowpack.dev/).
Currently `xstyled` is unusable and iam getting following build time error:
```
[snowpack] Cannot find module '/Users/bartosz/dev/market/ui/node_modules/@xstyled/styled-components/dist/styled-components.esm.js' from '/Users/bartosz/dev/market/ui/node_modules/snowpack/lib'
```

fix: styled components module name

---

packages/babel-preset-emotion-css-prop/src/index.ts
website/pages/docs/getting-started/migrate-from-emotion.mdx

Im just adding the [importMap](https://emotion.sh/docs/@emotion/babel-plugin#importmap) option to the babel plugin.
Although it does not really fix these issues https://github.com/gregberge/xstyled/issues/285 and https://github.com/gregberge/xstyled/issues/286, it is still useful in case you want to walk around this other one https://github.com/emotion-js/emotion/issues/2413 😅

Add importMap to the babel plugin

---

packages/system/src/types.ts

Currently, auto-completion for responsive and states utility does not work. This is due to an error in the ThemeVariants type. The current ThemeVariants definition is `{ _: number; xs: number, ... } | { _: null; hover: string; ... }`, which is actually treated as `never` . To fix this, it is necessary to remove the inconsistency of `_` and join them with `&` .
Original:
FIxed:

Fix wrong type for ThemeVariants

---

packages/util/src/index.ts

`@xstyled/util` is vulnerable to Prototype Pollution. This package allowing for modification of prototype behavior, which may result in Information Disclosure/DoS/RCE.
`util.merge({}, JSON.parse('{"__proto__":{"polluted":"Yes! Its Polluted"}}'));`
Vulnerable line of code:
https://github.com/gregberge/xstyled/blob/46145a69a288b695313d20c5c5182939139267d8/packages/util/src/index.ts#L78

Fix for Prototype Pollution

---

packages/system/src/types.ts

Fixes #308 
This change leverages TS 4.1+ template literal types to enable deep path autocomplete for theme values.
For a theme like this:
```ts
const theme = {
colors: {
brandGreen: '#2B968F',
uiButton: {
_: '#FF0',
hover: '#F00',
}
}
} as const
```
Instead of just receiving `'brandGreen' | 'uiButton'` as an autocomplete option for color props, `'uiButton._' | 'uiButton.hover'` would also be surfaced.
Some beta testing is probably warranted.

feat(typings): assemble deep paths for autocompletion

---

packages/emotion/src/createCreateGlobalStyle.tsx

Fix createGlobalStyle in @xstyled/emotion to work the same way as its styled-components counterpart.
```tsx
import { createGlobalStyle } from "@xstyled/emotion";
// This doesn't work
const GlobalStyle = createGlobalStyle<Props>`
...
`
import { createGlobalStyle } from "@xstyled/styled-components";
// This works as expected
const GlobalStyle = createGlobalStyle<Props>`
...
`
```

fix(types): fix emotion createGlobalStyle type def

---

packages/system/src/styles/flexboxes.ts

I want to use `flexBasis` for the same purpose as `flexShrink` in typescript.
But currently `flexBasis` is not available in typescript.
code completion is not work
code completion is work

fix FlexboxesProps to include FlexBasisProps

---

packages/system/src/styles/borders.test.ts
packages/system/src/styles/borders.ts
website/pages/docs/borders/border-style.mdx

The properties are not taken into account :
- borderTopStyle
- borderRightStyle
- borderBottomStyle
- borderLeftStyle
See new tests in `packages/system/src/styles/borders.test.ts`

feat: add border positions style helpers

---

packages/system/src/style.ts
packages/system/src/types.ts

As the title states, the goal of this MR is to infer automatically the return type of the `compose` method and also support the existing type in order not to create a breaking change in that area.
Before, in order to have the correct return type, you'd have to explicitly provide the "computed" return type:
```ts
interface GridItemProps extends GridAreaProps, GridColumnProps, GridRowProps {}
const gridItem = compose<GridItemProps>(gridArea, gridColumn, gridRow);
```
With this new change, you'd still be able to do that (like we do internally on xstyled) or you could just write the following:
```ts
const gridItem = compose(gridArea, gridColumn, gridRow);
// generated return type
// StyleGenerator<GridAreaProps<Theme> & GridColumnProps<Theme> & GridRowProps<Theme>>
```

impr(typing): infer automatically the typing of the generators used inside of the compose

---

packages/system/src/styles/borders.ts
packages/system/src/styles/flexboxes.ts
packages/system/src/styles/layout.ts
packages/system/src/styles/sizing.ts
packages/system/src/styles/space.ts
packages/system/src/styles/typography.ts

Based on the code itself and the website, some declarations don't match the actual typing of some props.
For instance, [sizing](https://xstyled.dev/docs/max-height/#fixed-max-height) props such as `w`/`h` or even `border`/`borderWidth` should accept any valid number (not only the numbers defined in the theme).
"Any valid value is accepted in width, numbers are converted to px, other units have to be specified."
So, I went through all the exposed props and I've updated the typing to add the missing valid type which is `number` in this case.

fix(typing): Support any valid number for utility props that needs it

---

packages/system/src/styles/borders.ts

I added outlineOffset prop to the code because this property was missing. This is also missing a theme getter due to the outline properties getters using the border ones. There is nothing like `border-offset` in CSS so I omitted it. I have never contributed to other open-source projects other than mine so if there are any errors in my code, please let me know and I'll try my best to fix it.

Adding outline offset property

---

packages/system/src/style.test.ts
packages/system/src/style.ts

Example: `<x.div color={{ '&:empty': 'red' }}/>`
This makes it, so we fall back to `&:empty` when `theme.states['&:empty']` and `theme.breakpoints['&:empty']` is not defined,
just like we use `red` when `theme.colors.red` is not defined.
I added unit tests, if there are more test cases I should take a look at, let me know.
I also tried it out using x from the `styled-components` package.

feat: added inline variants #333

---

website/pages/docs/core-concepts/hover-focus-and-other-states.mdx

A single ampersand refers to the static component selector which will have unintended effects when the styled-components babel plugin is also used. Double ampersand refers to an instance of the component, e.g. a specific `<x.div>` not ALL `<x.div>`.

update documentation for dark mode state

---

website/pages/docs/typography/list-style-type.mdx

The `listStyleType` [examples on the website](https://xstyled.dev/docs/list-style-type/#list-style-type) look like this:
The problem is that smooth-doc supplies a nested style for unordered lists, and `<x.div>` can't override it.
Make a PR and see if it worked :stuck_out_tongue_winking_eye:

fix(website): listStyleType examples

---

packages/emotion/src/index.ts

If you'd like to import `cssCreate` function with xstyled/emotion, `xstyled/packages/styled-components/src/create.ts` module should be exported in the index file.
* https://github.com/gregberge/xstyled/issues/295

export xstyled/packages/emotion/src/create.ts

---

packages/system/src/style.test.ts
packages/system/src/theme.ts

Move at-rules to the end of sorted styles, so that nested states can override. Fixes #288 
This _almost_ works:
```diff
-   const variants = { ...medias, ...states }
+   const variants = { ...states, ...medias }
```
but it's not enough, because `states` can contain at-rules too. The xstyled-provided `states` already does, and the developer could also supply their own, for instance with `@supports`
so instead we explicitly move at-rules to the end, similar to the way that `sortStyles` works.
Added a new test to ensure that rules are emitted in order. Without the code change, it fails like this:
```
FAIL  packages/system/src/style.test.ts
● #style › #style › works with variants
expect(received).toEqual(expected) // deep equality
- Expected  - 8
+ Received  + 8
{
"fontFamily": "title",
- …
```

fix: move at-rules to end of nested responsive states

---

website/pages/docs/core-concepts/hover-focus-and-other-states.mdx

This is the documentation for the feature I added in #334.
I tested this manually.

docs: added inline states to hover-focus-other-states page

---

packages/system/src/style.ts

Following this issue https://github.com/gregberge/xstyled/issues/371, I investigated the source code of xstyled to understand what was happening by adding logs:
```diff
// node_modules/@xstyled/system/dist/index.cjs (v3.6.0)
const getStyleFactory = (prop, mixin, themeGet) => {
return (props) => {
const fromValue = (value2) => {
if (!util.is(value2))
return null;
if (util.obj(value2))
return reduceVariants(props, value2, fromValue);
return util.cascade(mixin(themeGet ? themeGet(value2)(props) : value2), props);
};
const value = props[prop];
if (!util.is(value))
return null;
const cache = getCache(props.theme, prop);
if (cache.has(value)) {
+     console.log('--- cache.has --- (getStyleFactory)', value)
return cache.get(value);
}
const style2 = fromValue(props[prop]);
+   console.log('--- …
```

fix: stringify keys on cache

---

packages/system/src/colors.test.ts
packages/system/src/colors.ts

Current implementation works great for values greater that 7 but for values below 7 the hex alpha value is missing one extra digit. Fixed that by appending a zero to the value.
- #ffffff -> #ffffff3 (❌)
- #ffffff -> #ffffff03 (✅)

fix: Fixed incomplete hex alpha value generation

---

website/pages/docs/customization/cache.mdx

Change the slug and title for the new cache documentation page

docs: fix link to cache documentation

---

packages/system/src/styles/colors.ts

Explicitly do not allow arbitrary strings. The point is to ensure that if you're trying to enter a theme variable it correctly emits a  type error for typos and such.

feat: stricter color type

---

website/pages/docs/core-concepts/magic-styled-components.mdx

description is for xstyled, not styled.
```
const Box = styled.div({
margin: 2, // '2px' (not transformed by xstyled)
marginTop: '2', // '8px' (transformed by styled)
})
```
and description of value conversion by theme is insufficient.
Just document update.

docs: add styled rules description supplement

---

website/pages/docs/core-concepts/magic-styled-components.mdx

The description for media query in `magic-styled-components.mdx` is looks like incorrect.
at https://xstyled.dev/docs/magic-styled-components/#automatic-theming.
Just document update.

Fix media query description in magic-styled-components.mdx
