packages/styled-components/.size-snapshot.json, packages/styled-components/src/index.js
=> fix: explicit exports from styled-components

packages/styled-components/src/styled.js, packages/styled-components/src/styled.test.js
=> fix: support .attrs method

package.json, packages/styled-components/src/Box.js, packages/styled-components/src/Box.test.js, packages/styled-components/src/css.test.js, packages/styled-components/src/styled.test.js, packages/system/tests/styled-components/th.test.js, yarn.lock
=> fix: increase box specificity

website/src/pages/docs/motivation.mdx
I noticed a few small grammar mistakes, so I wanted to make these changes in hopes of improving the docs. I'm no English major, so some of my updates might need some tweaking, but I think the changes help this section read more clearly.
Read this section to see if it flows better and still makes sense.
Thanks!
=> Copy and grammar edits to the "Motivation" section

packages/styled-components/src/propGetters.js, packages/system/src/styles/borders.js, packages/system/src/th.js, packages/system/tests/styled-components/th.test.js
=> fix: add border-width utility

packages/emotion/src/Box.test.js, packages/emotion/src/createGlobalStyle.test.js, packages/emotion/src/css.test.js, packages/emotion/src/cx.test.js, packages/emotion/src/jsx.test.js, packages/emotion/src/styled.test.js, packages/styled-components/src/Box.test.js, packages/styled-components/src/createGlobalStyle.js, packages/styled-components/src/createGlobalStyle.test.js, packages/styled-components/src/css.test.js, packages/styled-components/src/styled.test.js, packages/system/tests/styled-components/breakpoints.test.js, packages/system/tests/styled-components/styles.test.js, packages/system/tests/styled-components/th.test.js
=> Fix createGlobalStyle

package.json, packages/system/src/style.js, packages/system/src/style.test.js, packages/system/src/styles/index.js, packages/system/src/styles/xgrids.js, packages/system/src/styles/xgrids.test.js, packages/system/src/unit.js, packages/system/src/unit.test.js, website/src/pages/docs/system-props.mdx, website/src/pages/docs/system-utilities.mdx
=> feat: add xgrids (bootstrap like grids)

package.json, packages/core/src/propGetters.js, packages/system/src/style.test.js, packages/system/src/styles/space.js, packages/system/src/util.test.js, packages/system/tests/styled-components/th.test.js
=> Various fixes

packages/core/src/propGetters.js, packages/system/src/styles/borders.js, packages/system/src/styles/index.js, packages/system/src/styles/shadows.js, website/src/pages/docs/system-props.mdx
Text shadows are not integrated into the library, although the documentation mentions it in the theme specification.
```
yarn build
yarn test
yarn lint
```
=> Add support for text-shadow

package.json, packages/core/src/colorModes.js, packages/core/src/colorModes.test.js, packages/core/src/customProperties.js, packages/core/src/customProperties.test.js, packages/core/src/index.js, packages/emotion/src/colorModes.js, packages/emotion/src/colorModes.test.js, packages/emotion/src/index.js, packages/styled-components/src/colorModes.js, packages/styled-components/src/colorModes.test.js, packages/styled-components/src/index.js, website/src/pages/docs/color-modes.mdx
=> feat: add color modes (dark mode)

packages/core/src/colorModes.js, packages/core/src/colorModes.test.js
=> fix(color-mode): fix color mode issues

packages/core/src/colorModes.js
=> fix: sync system color mode

website/package.json, website/src/components/LiveButtons.js, website/src/pages/index.mdx, website/yarn.lock
=> docs: dark mode on website

website/src/pages/docs/grid.mdx
=> feat: add grid doc

website/src/pages/docs/color-modes.mdx, website/src/pages/docs/emotion.mdx, website/src/pages/docs/getting-started.mdx, website/src/pages/docs/motivation.mdx, website/src/pages/docs/responsive.mdx, website/src/pages/docs/system-components.mdx, website/src/pages/docs/system.mdx, website/src/pages/docs/theming.mdx, website/src/pages/docs/transformers.mdx, website/src/pages/docs/variants.mdx
I have been really enjoying using xstyled in my recent projects and wanted to contribute more than just a one letter PR to help improve the documentation. I went through the main docs and tried to identify anywhere that still had some unclear descriptions and found a few spelling issues and put this PR together
Should just be documentation updates and should not required testing
=> docs: general grammar and spelling updates

website/src/pages/docs/system-utilities.mdx
if you visit `https://www.smooth-code.com/open-source/xstyled/docs/responsive` directly,  will go to a broken page.
=> docs: Fix broken url

website/src/pages/docs/responsive.mdx
I had to change the import locations to get this feature to work properly.
=> Update import locations

packages/core/src/propGetters.js
`outline-color` values are not being replaced properly.
=> fix(core): add outline-color to propGetters

packages/core/src/propGetters.js
Noticed this typo when looking for border prop info
=> fix: border typo in proptypes

website/src/pages/docs/responsive.mdx
Box isn't exported from `system`. Updated to correct import
=> docs: import box from styled components

packages/core/src/propGetters.js, packages/system/src/styles/backgrounds.js, packages/system/src/styles/typography.js, packages/system/tests/styled-components/styles.test.js, website/src/pages/docs/style-props.mdx, website/src/pages/docs/theme-specification.mdx
=> Various features

website/src/pages/docs/prop-types.mdx
Fix [prop-types documentation page](https://xstyled.dev/docs/prop-types/#how-to-get-prop-types) to changing `getUtilityPropTypes` with `getSystemPropTypes` as per https://github.com/smooth-code/xstyled/blob/master/packages/prop-types/src/index.js#L3
Run the website and verify the text is updated.
=> Fix prop-types documentation page 

packages/core/src/propGetters.js, packages/core/src/propGetters.test.js
=> feat(xstyled): support multiple values in box-shadow, text-shadow

packages/core/src/colorModes.js
The local storage is not always available. 
Load a page using xstyled and the color mode in an iframe with the "Block third party cookies" in chrome enabled.
=> fix(styled-components): local storage not available

benchmarks/README.md, benchmarks/emotion.js, benchmarks/package.json, benchmarks/src/App.js, benchmarks/src/components/EmotionTable.js, benchmarks/src/components/XStyledEmotionTable.js, benchmarks/yarn.lock
I was curious to see how `@xstyled/emotion` compares to `@emotion/styled`. I added a benchmark for it using the styled-components one as a template. 🙂 
None 😱
=> chore: added emotion benchmark

packages/system/src/styles/index.ts, packages/system/src/styles/svg.ts
=> feat: support "fill" & "stroke" properties

packages/system/src/styles/basics.test.ts, packages/system/src/styles/basics.ts, packages/system/src/styles/typography.ts, packages/system/src/unit.ts
=> feat: allow to configure rootFontSize

README.md
Fix broken quick links in README.
=> Fix broken quick links in README

website/pages/docs/sizing/height.mdx
=> Fix docs typos

website/pages/docs/getting-started/upgrade-guide.mdx
I'm currently upgrading xstyled and I saw a small typo 🙂
=> docs: fix styled/x typo

website/pages/docs/spacing/margin.mdx
=> docs: fix p/m typo

packages/system/src/styles/animations.ts, packages/system/src/styles/backgrounds.ts, packages/system/src/styles/borders.ts, packages/system/src/styles/effects.ts, packages/system/src/styles/flexbox-grids.ts, packages/system/src/styles/flexboxes.ts, packages/system/src/styles/grids.ts, packages/system/src/styles/index.ts, packages/system/src/styles/interactivity.ts, packages/system/src/styles/layout.ts, packages/system/src/styles/sizing.ts, packages/system/src/styles/space.ts, packages/system/src/styles/svg.ts, packages/system/src/styles/tables.ts, packages/system/src/styles/transforms.ts, packages/system/src/styles/transitions.ts, packages/system/src/styles/typography.ts
=> chore: use interface instead of types

packages/core/src/propGetters.ts
=> fix(styled): use space in column-gap & row-gap

packages/system/src/styles/flexboxes.ts
=> fix(types): add missing alignContent prop

packages/system/src/styles/sizing.ts, website/pages/docs/sizing/max-height.mdx, website/pages/docs/sizing/max-width.mdx, website/pages/docs/sizing/min-height.mdx, website/pages/docs/sizing/min-width.mdx
=> feat: add maxW, maxH, minW, minH shortcuts

website/pages/docs/getting-started/migrate-from-styled-components.mdx
=> docs(website): document babel-macros support

benchmarks/package.json, package.json, packages/system/src/defaultTheme.ts, packages/system/src/styles/typography.test.ts, packages/system/src/styles/typography.ts, packages/system/src/types.ts, website/pages/docs/typography/text.mdx, website/partials/customizing/line-heights.mdx, yarn.lock
=> feat(text): new text utility

website/pages/docs/getting-started/installation.mdx, website/pages/docs/getting-started/migrate-from-emotion.mdx
The purpose of this PR is to help other devs integrate emotion with xstyled with less frustration.
=> update documentation for setting up emotion's babel plugin

CONTRIBUTING.md, packages/system/src/styles/space.ts
Hi @gregberge, Kevin here from Eesel :) 
I noticed this typo while using the lib so I made a small PR. Not sure how you want to manage retro compatibility if necessary.
Also not a blocker since I actually use `pb` alias.
=> chore(system): fix paddingBottom typo

packages/core/src/transform.ts
Fixes #247 on next
Cherry pick of e620935
=> fix(transform): IE11 doesn't support dotAll (#247)

packages/emotion/src/createX.ts, packages/styled-components/src/createX.ts
- fix(emotion): fix color prop
- refactor: rename type
=> fix color prop

packages/system/src/transformers.test.ts, packages/system/src/unit.test.ts, packages/system/src/unit.ts
=> fix(system): fix rpx transformers

packages/system/src/defaultTheme.ts
=> fix(breakpoints): add _ into breakpoints

website/pages/docs/core-concepts/magic-styled-components.mdx
=> #302 Added a missing paren in the code example

packages/system/src/types.ts
=> fix: support numbers corresponding to theme property keys

build/rollup.config.js, package.json, packages/babel-preset-emotion-css-prop/package.json, packages/core/package.json, packages/emotion/package.json, packages/emotion/src/createStyled.ts, packages/emotion/src/createX.ts, packages/emotion/src/emStyled.ts, packages/prop-types/package.json, packages/styled-components/package.json, packages/styled-components/src/createStyled.ts, packages/styled-components/src/createX.ts, packages/styled-components/src/css.test.tsx, packages/styled-components/src/scStyled.ts, packages/system/package.json, packages/util/package.json
=> fix(esm): fix module exports

packages/system/src/styles/typography.test.ts, packages/system/src/styles/typography.ts, website/pages/docs/typography/text.mdx
=> feat: add ability to customize spacing properties in "texts"

packages/system/src/styles/animations.ts, packages/system/src/styles/borders.ts, packages/system/src/styles/flexbox-grids.ts, packages/system/src/styles/flexboxes.ts, packages/system/src/styles/grids.ts, packages/system/src/styles/layout.ts, packages/system/src/styles/sizing.ts, packages/system/src/styles/space.ts, packages/system/src/styles/transforms.ts, packages/system/src/styles/transitions.ts, packages/system/src/styles/typography.ts
=> fix(types): fix missing values in types

package-lock.json, packages/core/package.json
=> fix(core): add missing util

CONTRIBUTING.md
=> fix: fixed contributing guide setup step documentation

website/pages/docs/core-concepts/magic-styled-components.mdx, website/pages/docs/typography/font-style.mdx
Changed fontSize to fontStyle
+Fixed typo in code example
=> fix: Fixed typo in font style example

packages/emotion/src/create.ts, packages/emotion/src/index.ts, packages/styled-components/src/create.ts, packages/styled-components/src/index.ts
fixes #391 by adding necessary imports. Similar to PR #372 which looks abandoned
Doesn't really change the code, only adds type exports to fix the TS error. All tests still pass.
=> fix(types): export XStyled, X, XStyledSet

packages/core/src/breakpoints.ts
Fixes issue #389 as per @agriffis recommendation
=> Fix incorrect breakpoint calculation (Fixes #389)
